### ISSUE TITLE
npm start报错，run dev也是

### ISSUE THREAD

**Issue by aogg** [zhqlol/edgarserver#1]
npm start报错，run dev也是

在cnpm i之后

```code

> edgar-server@0.4.0 start /Applications/www/github/node/edgarserver
> cross-env EGG_SERVER_ENV=prod NODE_ENV=production egg-scripts start --port=38083 --daemon --title=edgar-server

[egg-scripts] Starting egg application at /Applications/www/github/node/edgarserver
[egg-scripts] Run node /Applications/www/github/node/edgarserver/node_modules/_egg-scripts@2.9.1@egg-scripts/lib/start-cluster {"port":38083,"title":"edgar-server","framework":"/Applications/www/github/node/edgarserver/node_modules/egg","baseDir":"/Applications/www/github/node/edgarserver"} --title=edgar-server
[egg-scripts] Save log file to /Users/code/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] tail -n 100 /Users/code/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] /Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/application.js:69
[egg-scripts]       throw e;
[egg-scripts]       ^
[egg-scripts] 
[egg-scripts] TypeError: Cannot read property 'captcha' of undefined
[egg-scripts]     at module.exports.app (/Applications/www/github/node/edgarserver/app/router/public.js:10:53)
[egg-scripts]     at getExports (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:220:15)
[egg-scripts]     at FileLoader.parse (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:158:25)
[egg-scripts]     at FileLoader.load (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:67:24)
[egg-scripts]     at AppWorkerLoader.app.loader.loadRouter (/Applications/www/github/node/edgarserver/node_modules/_egg-router-plus@1.2.2@egg-router-plus/app.js:30:8)
[egg-scripts]     at AppWorkerLoader.load (/Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/loader/app_worker_loader.js:41:10)
[egg-scripts]     at new Application (/Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/application.js:65:19)
[egg-scripts]     at Object.<anonymous> (/Applications/www/github/node/edgarserver/node_modules/_egg-cluster@1.19.1@egg-cluster/lib/app_worker.js:20:13)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[egg-scripts] /Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/application.js:69
[egg-scripts]       throw e;
[egg-scripts]       ^
[egg-scripts] 
[egg-scripts] TypeError: Cannot read property 'captcha' of undefined
[egg-scripts]     at module.exports.app (/Applications/www/github/node/edgarserver/app/router/public.js:10:53)
[egg-scripts]     at getExports (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:220:15)
[egg-scripts]     at FileLoader.parse (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:158:25)
[egg-scripts]     at FileLoader.load (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:67:24)
[egg-scripts]     at AppWorkerLoader.app.loader.loadRouter (/Applications/www/github/node/edgarserver/node_modules/_egg-router-plus@1.2.2@egg-router-plus/app.js:30:8)
[egg-scripts]     at AppWorkerLoader.load (/Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/loader/app_worker_loader.js:41:10)
[egg-scripts]     at new Application (/Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/application.js:65:19)
[egg-scripts]     at Object.<anonymous> (/Applications/www/github/node/edgarserver/node_modules/_egg-cluster@1.19.1@egg-cluster/lib/app_worker.js:20:13)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[egg-scripts] /Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/application.js:69
[egg-scripts]       throw e;
[egg-scripts]       ^
[egg-scripts] 
[egg-scripts] TypeError: Cannot read property 'captcha' of undefined
[egg-scripts]     at module.exports.app (/Applications/www/github/node/edgarserver/app/router/public.js:10:53)
[egg-scripts]     at getExports (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:220:15)
[egg-scripts]     at FileLoader.parse (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:158:25)
[egg-scripts]     at FileLoader.load (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:67:24)
[egg-scripts]     at AppWorkerLoader.app.loader.loadRouter (/Applications/www/github/node/edgarserver/node_modules/_egg-router-plus@1.2.2@egg-router-plus/app.js:30:8)
[egg-scripts]     at AppWorkerLoader.load (/Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/loader/app_worker_loader.js:41:10)
[egg-scripts]     at new Application (/Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/application.js:65:19)
[egg-scripts]     at Object.<anonymous> (/Applications/www/github/node/edgarserver/node_modules/_egg-cluster@1.19.1@egg-cluster/lib/app_worker.js:20:13)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[egg-scripts] /Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/application.js:69
[egg-scripts]       throw e;
[egg-scripts]       ^
[egg-scripts] 
[egg-scripts] TypeError: Cannot read property 'captcha' of undefined
[egg-scripts]     at module.exports.app (/Applications/www/github/node/edgarserver/app/router/public.js:10:53)
[egg-scripts]     at getExports (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:220:15)
[egg-scripts]     at FileLoader.parse (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:158:25)
[egg-scripts]     at FileLoader.load (/Applications/www/github/node/edgarserver/node_modules/_egg-core@4.9.1@egg-core/lib/loader/file_loader.js:67:24)
[egg-scripts]     at AppWorkerLoader.app.loader.loadRouter (/Applications/www/github/node/edgarserver/node_modules/_egg-router-plus@1.2.2@egg-router-plus/app.js:30:8)
[egg-scripts]     at AppWorkerLoader.load (/Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/loader/app_worker_loader.js:41:10)
[egg-scripts]     at new Application (/Applications/www/github/node/edgarserver/node_modules/_egg@2.10.0@egg/lib/application.js:65:19)
[egg-scripts]     at Object.<anonymous> (/Applications/www/github/node/edgarserver/node_modules/_egg-cluster@1.19.1@egg-cluster/lib/app_worker.js:20:13)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[egg-scripts] 2018-08-30 14:32:03,338 ERROR 17969 nodejs.AppWorkerDiedError: [master] app_worker#3:17973 died (code: 1, signal: null, suicide: false, state: dead), current workers: ["1","2","4"]
[egg-scripts]     at Master.onAppExit (/Applications/www/github/node/edgarserver/node_modules/_egg-cluster@1.19.1@egg-cluster/lib/master.js:388:21)
[egg-scripts]     at Master.emit (events.js:182:13)
[egg-scripts]     at Messenger.sendToMaster (/Applications/www/github/node/edgarserver/node_modules/_egg-cluster@1.19.1@egg-cluster/lib/utils/messenger.js:133:17)
[egg-scripts]     at Messenger.send (/Applications/www/github/node/edgarserver/node_modules/_egg-cluster@1.19.1@egg-cluster/lib/utils/messenger.js:98:12)
[egg-scripts]     at EventEmitter.cluster.on (/Applications/www/github/node/edgarserver/node_modules/_egg-cluster@1.19.1@egg-cluster/lib/master.js:265:22)
[egg-scripts]     at EventEmitter.emit (events.js:187:15)
[egg-scripts]     at ChildProcess.worker.process.once (internal/cluster/master.js:194:13)
[egg-scripts]     at Object.onceWrapper (events.js:273:13)
[egg-scripts]     at ChildProcess.emit (events.js:182:13)
[egg-scripts]     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
[egg-scripts] name: "AppWorkerDiedError"
[egg-scripts] pid: 17969
[egg-scripts] hostname: code-aodeMacBook-Pro.local
[egg-scripts] 
[egg-scripts] 2018-08-30 14:32:03,339 ERROR 17969 [master] app_worker#3:17973 start fail, exiting with code:1
[egg-scripts] 2018-08-30 14:32:03,340 ERROR 17969 [master] exit with code:1
[egg-scripts] 2018-08-30 14:32:03,344 ERROR 17970 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
[egg-scripts] 2018-08-30 14:32:03,346 ERROR 17970 [agent_worker] exit with code:110
[egg-scripts] 
[egg-scripts] Start got error, see /Users/code/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edgar-server@0.4.0 start: `cross-env EGG_SERVER_ENV=prod NODE_ENV=production egg-scripts start --port=38083 --daemon --title=edgar-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the edgar-server@0.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/code/.npm/_logs/2018-08-30T06_32_05_294Z-debug.log
```

**Comment by aogg** [comment]
app/controller/public/captcha.js
这个文件不存在，麻烦上传下，而且后台的用户管理也打不开

**Comment by zhqlol** [comment]
之前的.gitignore设置有点问题，本地一直没问题，就没注意…… 已经上传了
最近工作比较忙，一直没有更新，要等这阵忙完了之后才会继续更新后续功能

**Comment by aogg** [comment]
根目录也有public，是官方默认忽略的，也是需要被忽略的，只是你不是根目录的也被连带忽略了。
.gitignore要改成只忽略根目录的

**Comment by zhqlol** [comment]
嗯嗯，应该是这样的，我就简单粗暴的先把对应的文件传上来了
现在都是前后端分离，这个项目的初衷本来是想让前端童鞋可以使用自己熟悉的语言快乐的完成整个项目的搭建，不过就我们公司推广来看，前端的朋友们对向全栈进军的兴趣很一般……
其实我们公司的项目目前nodeServer已经又被单独的拉出来了，很是尴尬

**Comment by meixuan666** [comment]
这个项目是一个后台管理的项目，但是看您的东西，应该是全栈，但是我现在需要改成一个前台网站，可以用这个改吗，我改了一下午，也只改了一个登录页，好多东西不能动，还有这个您的代码逻辑我也弄不太懂。但是因为您的项目跟node后台不冲突才让我用的这个，您看改您这个项目这个做法可行吗。

**Comment by meixuan666** [comment]
node后台

**Comment by zhqlol** [comment]
其实我就是把iview-admin和egg做了下整合，而iview-admin的设计初衷更偏向于中后台解决方案，如果你只是想做个简单门户、论坛之类的应该没啥问题。
你可以去了解一下antd，看看这类解决方案的设计思路，他对自己的介绍要更详细一些。
如果你就是想vue+一个nodeServer，可以去了解一下easywebpack项目。

**Comment by meixuan666** [comment]
也就是您的项目也可以改成简单的门户，主要是我做的东西跟后台冲突，然后Boss说让我用您这个作为模板，我死活改不好，antd和easywebpack这俩个可以跟后台整合吗

**Comment by zhqlol** [comment]
如果就是简单门户的话是没有问题的。我不了解你为什么要使用一个nodeServer，看你的意思你们是有后端的，如果有服务端的话为什么不直接就用前后端分离的方式呢？
NodeServer就算是有egg这种企业级解决方案，还是更偏向于做服务转发，想替掉服务端还是有局限
你修改中具体遇到了什么问题呢？

**Comment by meixuan666** [comment]
很多问题，跟我项目没有关系的组件我没办法删除，然后我添加的页面显示不了，页面404，还有您的逻辑我缕不清楚，我首页改好了是因为我把您的主页注释了，添加不进去我自己的东西。其实我用不到Egg的，我只是用vue做的简单的网站，我也不知道我做的东西为什么会跟后端冲突，老板就让我改。老板说后端使用node写的，我也不清楚。我现在该您的东西一点思路也没有，无从下手
